import type { AppState, Bakery, Listing } from "./types";

export const bakeries: Bakery[] = [
  {
    id: "bakery-sunrise",
    name: "Sunrise Bakery",
    address: "12 Jalan Genting Klang, Setapak",
    phone: "03 2188 9041",
    area: "Setapak",
    distanceKm: 0.6,
    rating: 4.8,
    ratingCount: 214,
    pickupSuccessRate: 97,
    verified: true,
    latitude: 3.203,
    longitude: 101.722,
  },
  {
    id: "bakery-little-oven",
    name: "Little Oven",
    address: "PV128, Setapak",
    phone: "03 7781 4402",
    area: "Setapak",
    distanceKm: 1.2,
    rating: 4.7,
    ratingCount: 119,
    pickupSuccessRate: 95,
    verified: true,
    latitude: 3.198,
    longitude: 101.715,
  },
  {
    id: "bakery-bread-yard",
    name: "Bread Yard",
    address: "Setapak Central, Jalan Taman Ibu Kota",
    phone: "03 4141 8800",
    area: "Setapak",
    distanceKm: 2.4,
    rating: 4.6,
    ratingCount: 88,
    pickupSuccessRate: 92,
    verified: true,
    latitude: 3.207,
    longitude: 101.711,
  },
  {
    id: "bakery-moonlight",
    name: "Moonlight Bakes",
    address: "Danau Kota, Kuala Lumpur",
    phone: "03 4022 7301",
    area: "Danau Kota",
    distanceKm: 2.8,
    rating: 4.9,
    ratingCount: 63,
    pickupSuccessRate: 98,
    verified: true,
    latitude: 3.211,
    longitude: 101.707,
  },
];

export const listings: Listing[] = [
  {
    id: "listing-sourdough-bundle",
    bakeryId: "bakery-sunrise",
    title: "Sourdough end-of-day bundle",
    category: "bundle",
    description: "Mixed sourdough slices, milk buns, and croissants packed after the evening count.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80",
    originalPrice: 14,
    discountedPrice: 6,
    quantityTotal: 3,
    quantityAvailable: 3,
    pickupStart: "6:30 PM",
    pickupEnd: "8:00 PM",
    pickupEndMinutes: 20 * 60,
    bakedLabel: "Baked today",
    ingredients: "Sourdough, milk buns, butter croissants.",
    allergens: "Contains wheat, milk, egg. May contain nuts.",
    status: "active",
    createdAt: "2026-06-21T10:00:00+08:00",
  },
  {
    id: "listing-pastry-box",
    bakeryId: "bakery-little-oven",
    title: "Croissant and pastry rescue box",
    category: "pastry",
    description: "A small box of butter croissants, Danish pastries, and sweet buns.",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1200&q=80",
    originalPrice: 18,
    discountedPrice: 9,
    quantityTotal: 1,
    quantityAvailable: 1,
    pickupStart: "5:45 PM",
    pickupEnd: "7:00 PM",
    pickupEndMinutes: 19 * 60,
    bakedLabel: "Packed after closing count",
    ingredients: "Croissants, Danish pastries, custard buns.",
    allergens: "Contains wheat, milk, egg.",
    status: "active",
    createdAt: "2026-06-21T09:30:00+08:00",
  },
  {
    id: "listing-wholemeal-pair",
    bakeryId: "bakery-bread-yard",
    title: "Wholemeal loaf pair",
    category: "bread",
    description: "Two sliced wholemeal loaves baked this morning, packed for same-day pickup.",
    image: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=1200&q=80",
    originalPrice: 12,
    discountedPrice: 7,
    quantityTotal: 5,
    quantityAvailable: 5,
    pickupStart: "7:00 PM",
    pickupEnd: "9:00 PM",
    pickupEndMinutes: 21 * 60,
    bakedLabel: "Best before tomorrow",
    ingredients: "Wholemeal flour, yeast, salt, water.",
    allergens: "Contains wheat.",
    status: "active",
    createdAt: "2026-06-21T11:00:00+08:00",
  },
  {
    id: "listing-cream-bun-bag",
    bakeryId: "bakery-moonlight",
    title: "Cream bun mixed bag",
    category: "bundle",
    description: "Assorted cream buns and soft rolls. Exact mix depends on what remains after closing count.",
    image: "https://images.unsplash.com/photo-1587241321921-91a834d6d191?auto=format&fit=crop&w=1200&q=80",
    originalPrice: 16,
    discountedPrice: 8,
    quantityTotal: 2,
    quantityAvailable: 2,
    pickupStart: "8:00 PM",
    pickupEnd: "9:30 PM",
    pickupEndMinutes: 21 * 60 + 30,
    bakedLabel: "Baked today",
    ingredients: "Soft buns, pastry cream, butter rolls.",
    allergens: "Contains wheat, milk, egg.",
    status: "active",
    createdAt: "2026-06-21T12:00:00+08:00",
  },
];

export function createInitialState(): AppState {
  return {
    bakeries: structuredClone(bakeries),
    listings: structuredClone(listings),
    orders: [],
    savedListingIds: [],
    reportedListingIds: [],
    session: { role: "guest", name: "Guest" },
    activeFilter: "all",
    activeView: "market",
    browseMode: "list",
    area: "Setapak",
    radiusKm: 3,
    searchQuery: "",
  };
}
